### ISSUE TITLE
Splash Screen UI

### ISSUE THREAD

**Issue by utkarsh0702** [utkarsh0702/Pothole-Detection-Visualization#2]

**Comment by Hardikkr** [comment]
There's no app in this repo, contributors are supposed to add it right?

**Comment by utkarsh0702** [comment]
Added the flutter support.

**Comment by Hardikkr** [comment]
Can I add splash screen in this app?

**Comment by utkarsh0702** [comment]
You can

**Comment by Hardikkr** [comment]
We would need an icon at first, so that we could show that icon and the name of the app in the splash screen.

**Comment by utkarsh0702** [comment]
The apps Icon
![app_icon1](https://user-images.githubusercontent.com/35002267/101388782-6f8bd280-38e6-11eb-97e0-316e84c2fc37.png)
